---
- hosts: database
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes
      
  tasks: 

    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        name:
          - mysql-server-5.6
          - python-mysqldb
        state: latest #Indica que queremos sempre a ultima versão
      become: yes
    
      #Modulo para criar banco de dados mysql
    - name: 'Cria o banco MySql'
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present
    
    #Modulo para criar usuario dentro de um banco
    - name: 'Cria o usuário do MySQL'
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 12345
        priv: 'wordpress_db.*:ALL'
        state: present
        host: "{{ item }}"
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - '172.17.177.40'
      
    #copia arquivo my.cnf
    - name: 'Configura MySQL para aceitar conexões remotas'
      copy:
        src: 'files/my.cnf'
        dest: '/etc/mysql/my.cnf'
      become: yes #identificando copia como root
      notify: #Lista de handlers
        - restart mysql #Chamando handler criado do restart apache

- hosts: wordpress
  handlers:
    - name: restart apache
      service: 
        name: apache2
        state: restarted
      become: yes

  tasks: 
    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        name:
          - php5
          - apache2
          - libapache2-mod-php5
          - php5-gd
          - libssh2-php
          - php5-mcrypt
          - php5-mysql
        state: latest #Indica que queremos sempre a ultima versão
      become: yes
    
    #Modulo para baixar um arquivo para maquina destino direto que uma url 
    - name: 'Baixa o arquivo de instalacao do Wordpress'
      get_url:
        url: 'https://wordpress.org/wordpress-5.0.tar.gz'
        dest: '/tmp/wordpress.tar.gz'
    
    #Modulo para descompactar arquivo
    - name: 'Descompacta o wordpress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: /var/www/
        remote_src: yes
      become: yes
    
    #Modulo para copiar o arquivo wp-config-sample.php para
    #Um novo arquivo com o nome wp-config.php
    - copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes #Indica que o arquivo já está localizado na maquina destino
      become: yes # Indica que o bloco será feito pelo usuario root
    
    #Modulo de alteração do arquivo wp-config.php
    #onde encontrar os valores database_name_here,username_here e password_here
    #Substituir pelos valores wordpress_db, wordpress_user,12345
    - name: 'Configura o wp-config com as entradas do banco de dados'     
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db'}
        - { regex: 'username_here', value: 'wordpress_user'}
        - { regex: 'password_here', value: '12345'}
        - { regex: 'localhost', value: '172.17.177.42'}
      become: yes

    
    #Copiando files/00-default.conf para dentro da maquina virtual 
    #Configurando Wordpress com Apache
    - name: 'Configura Apache para servir o Wordpress'
      copy:
        src: 'files/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify: #Lista de handlers
        - restart apache #Chamando handler criado do restart apache

